"""empty message

Revision ID: 945cb722eb08
Revises: 
Create Date: 2020-03-29 10:51:14.807138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945cb722eb08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_puppies_id'), 'puppies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_puppies_id'), table_name='puppies')
    op.drop_table('puppies')
    # ### end Alembic commands ###
